### ISSUE TITLE
You can NOT use a directory as a part of $route['default_controller'] setting.

### ISSUE THREAD

**Issue by MohammedTamimi** [Ihsanit/Ayadaty#1]
`$route['default_controller'] = 'home_controllers/home_c/index';`

**The above code will not work,** because the $route['default_controller']  is supposed to accept a controller/method value only without any sub-directory.

* If you try to open http://localhost/ayadaty/ using the above settings, you will git error message: **404 Page Not Found**. Because the CodeIgniter will try to invoke the home_c function that inside the home_controllers which doesn't exist.

For more information: https://www.codeigniter.com/user_guide/general/routing.html#reserved-routes

The correct is:
`$route['default_controller'] = 'home_c/index';`
or
`$route['default_controller'] = 'home_c'; // because the index function is the default function.`

In general, I prefer to put all controllers inside the controllers directory itself,  not inside a sub-directory.
So, If you do not have a reason, please correct this point.

**Comment by RababMojahed** [comment]
oh,
sub-directories as precaution in case the files are be grown, we will omit them
