### ISSUE TITLE
Wildcards routes

### ISSUE THREAD

**Issue by MohammedTamimi** [Ihsanit/Ayadaty#2]
Routes will run in the order they are defined (From top to bottom), So higher routes will always take precedence over lower ones.

**Incorrect:**
```
$route['(:any)']='home_controllers/home_c/index';//URI specified
$route['default_controller'] = 'home_c/index';
```

**Correct:**
```
$route['default_controller'] = 'home_c/index';
$route['(:any)']='home_controllers/home_c/index';//URI specified
```

In your case, bot $route['default_controller'] and $route['(:any)'] will route to the same URI, so you will not detect this bug.

**As a basic rule, wildcards should be the last route condition.**

**Comment by RababMojahed** [comment]
Thanks on a note, well
