### ISSUE TITLE
Design the header, Home page, and footer.

### ISSUE THREAD

**Issue by MohammedTamimi** [Ihsanit/Ayadaty#4]
**Design the header, Home page, and footer.**

* You have to use any dummy data in this stage of development  in order to make the site appears realistically.

* You must include all sections described in the planning and requirement analysis page:
https://github.com/Ihsanit/Ayadaty/wiki/Planning-and-requirement-analysis

* Regarding to the footer, As you work as a team member of Ihsan IT, you have to mention that this site developed by Ihsan IT.

* Once you have starting designing this task, you have to move the card of this task from (To Do) column to the (In Progress) Column.

* If you want any questions, suggestions, or request more clarifications, you can leave comments on this issue.

Best regards

**Comment by RababMojahed** [comment]
Noted, 
The point of number two, I understand that you plan that website is in general through you said " Favorite clinics/ hospitals 3-5 only (based on selected location/cookies)" these hospitals at a city the result will be appeared the best depends on many principles, visitors' rating..etc. 
ok we may develop as stages

Changing the (To Do) to (In progress) from choosing labels,right?

**Comment by MohammedTamimi** [comment]
Drag&Drop cards form (To do) column to (In progress) column inside Kanban board.

1. Go to projects of Ihsanit organization: 
https://github.com/orgs/Ihsanit/projects

2. Click the project title [Medical Services Center]:
https://github.com/orgs/Ihsanit/projects/1

3.  Once you start any task, just drag and drop cards from To do-> In progress -> Done.
The progress of project status will updated automatically based on this board.

**Comment by RababMojahed** [comment]
well, I did it.

**Comment by MohammedTamimi** [comment]
Sorry for misunderstanding,
I said : 'The content of the page will not repeated on all pages', but the navigation bar will be repeated on all pages, so adding it within the header or separate file will lead to the same result.

**Comment by RababMojahed** [comment]
It's easy
